sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: jinse_flowershop
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 你的阿里云存储
    access-key-secret: 你的阿里云存储
    bucket-name: 你的阿里云存储
  redis:
    host: localhost
    port: 6379
    database: 0
    password: root
  wechat:
    appid: 
    secret: 
  alipay:
    biz-content-template: '{"out_trade_no":"%s","total_amount":"%s","subject":"%s","product_code":"FAST_INSTANT_TRADE_PAY"}'

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: flower-shop-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
